### ISSUE TITLE
Support for apiextensions.k8s.io/v1

### ISSUE THREAD

**Issue by kturcios** [dot-i/k8s-operator-node#10]
First of all, thank you for this! This has been really helpful for building an operator in JS.

I was wondering if you can add support for `apiextensions.k8s.io/v1` instead of `apiextensions.k8s.io/v1beta`. I pulled and tried to modify the Operator class, but when I made that change I was unable to receive any events after the first event.

**Comment by dot-i** [comment]
I've made some changes to support both `apiextensions.k8s.io/v1` and `apiextensions.k8s.io/v1beta1` in `registerCustomResourceDefinition()`. Other than that it required no changes to the watch itself.

Published as `1.1.0`.
