### ISSUE TITLE
Export class `ResourceMetaImpl`

### ISSUE THREAD

**Issue by pfisterer** [dot-i/k8s-operator-node#5]
I'm want to update the status of custom resources outside of event handlers. However, invoking `setResourceStatus` requires an instance of ResourceMetaImpl, which is available only in event handlers.

See https://github.com/pfisterer/edsc-dns-domains/blob/f8886556c1644718522913f982953417ac548fff/src/crd-watcher.js#L60 for my use case.

Would it be possible to export `ResourceMetaImpl` from the module?

**Comment by dot-i** [comment]
If you have a look at the example in `README.md` you can see there's a `meta` field on the resource event you received which implements the right interface:

```
await this.setResourceStatus(e.meta, {
    observedGeneration: metadata.generation
});
```

Is this for some reason not the right solution for you?

**Comment by pfisterer** [comment]
Thanks for your comment. The code above works for me. But I needed to update the status without an event.

The use case is that some the custom resource describes some desired state. When this state is reached, I want to update its status. But in this case, I do not have a corresponding event.

**Comment by dot-i** [comment]
OK, understood. I guess it wouldn't hurt to add an `export` to that class, certainly if it's indeed useful as you're pointing out.

**Comment by pfisterer** [comment]
Great, thank you!

**Comment by dot-i** [comment]
`1.0.7` was just published to `npm`: https://www.npmjs.com/package/@dot-i/k8s-operator

**Comment by pfisterer** [comment]
Great, works for me! Thanks a lot! 

If somebody coming across this issue, here's an example: https://github.com/pfisterer/edsc-microk8s-controller/blob/master/app/reconciler.js
